ports:
  - port: 8080
    visibility: public
image: gitpod/workspace-mysql
tasks:
  - name: "Dependencies & Database"
    init: |
          sdk install java 17.0.8-oracle < /dev/null
          sdk flush archives
          sdk flush temp